// build.js

import { defineConfig } from 'vite';
import banner from 'vite-plugin-banner'
const bannerContent = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository https://github.com/Myriad-Dreamin/typst.ts/blob/main/packages/typst.ts
*/`;

const component = process.argv.find((arg) => arg.startsWith('--component='));
const componentName = component ? component.split('=')[1] : 'main';

const entry = (name, path) => ({[name]: { name, entry: {[name]: `./src/${path}.mts`} }});

const libs = {
  ...entry('main', 'main'),
  ...entry('global-compiler', 'contrib/global-compiler'),
  ...entry('global-renderer', 'contrib/global-renderer'),
  ...entry('all-in-one-lite', 'contrib/all-in-one-lite'),
  ...entry('all-in-one', 'contrib/all-in-one'),
};

const lib = libs[componentName];
if (!lib) {
  console.error(`[typst.ts] Unknown component: ${componentName}`);
  process.exit(1);
}

// build
export default defineConfig({
  plugins: [banner(bannerContent)],
  configFile: false,
  build: {
    lib: {
      ...lib,
      formats: ['es', 'cjs'],
    },
    emptyOutDir: false,
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
      }
      // other options
    },
  },
});
