[package]
name = "typst-ts-fontctl"
description = "Font control for Typst.ts."
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

cmd_lib = "1.3.0"
anyhow.workspace = true
tempfile = "3"
sha2.workspace = true
hex.workspace = true

clap = { workspace = true, features = ["derive", "env", "unicode", "wrap_help"] }
clap_complete.workspace = true
clap_complete_fig.workspace = true
