[package]
name = "typst-ts-pdf-exporter"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"
description = "Export a frame of Typst document into a PDF document."
repository = "https://github.com/Myriad-Dreamin/typst.ts"

[dependencies]

typst.workspace = true

typst-ts-core.workspace = true
