[package]
name = "reflexo-vec2dom"
description = "Export a frame of Typst document into dom element."
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

typst.workspace = true
comemo.workspace = true

svgtypes.workspace = true
tiny-skia.workspace = true
tiny-skia-path.workspace = true

reflexo = { workspace = true, features = ["typst"] }
reflexo-typst2vec.workspace = true
reflexo-vec2canvas.workspace = true
reflexo-vec2sema.workspace = true
reflexo-vec2bbox.workspace = true
reflexo-vec2svg.workspace = true
log.workspace = true
async-recursion.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

js-sys.workspace = true
web-sys = { workspace = true, features = [
    "console",
    "HtmlDivElement",
    "HtmlTemplateElement",
    "SvgElement",
    "SvgGraphicsElement",
    "SvgsvgElement",
    "HtmlElement",
    "Window",
    "Document",
    "DocumentFragment",
    "CssStyleDeclaration",
] }

[features]
default = []
# "debug_repaint", "debug_repaint_svg", "debug_repaint_canvas"
no-content-hint = ["reflexo-typst2vec/no-content-hint"]
experimental-ligature = ["reflexo-typst2vec/experimental-ligature"]
aggresive-browser-rasterization = []
debug_repaint = []
debug_repaint_svg = []
debug_repaint_canvas = []
debug_repaint_semantics = []
debug_recalc_stage = []
debug_attach = []
debug_relayout = []
