import { spawnSync } from 'child_process';

const args = process.argv.slice(2);

const napiArgs = [
  'napi',
  'build',
  '--platform',
  '--release',
  '--dts-header',
  "/* auto-generated by NAPI-RS */ /* eslint-disable */ import type * as types from './index.js';",
  '--dts',
  'index-napi.d.ts',
  '--js',
  'index-napi.js',
  '--pipe',
  'prettier -w',
  ...args,
];

const YARN = process.platform === 'win32' ? 'yarn.cmd' : 'yarn';

const napi = spawnSync(YARN, napiArgs, { stdio: 'inherit' });
if (napi.error || napi.status !== 0) {
  console.log('napi', napi.status, napi.error);
  process.exit(napi.status);
}

const tsc = spawnSync(YARN, ['tsc'], { stdio: 'inherit' });
if (tsc.error || tsc.status !== 0) {
  console.log('tsc', tsc.status, tsc.error);
  process.exit(tsc.status);
}
