use std::{
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
};

use rayon::prelude::*;
use walkdir::WalkDir;

static PRESET_HEADER: &str = r#"
#import "/contrib/templates/std-tests/preset.typ": *
#show: test-page
"#;

static SUPPORT_HEADER: &str = r#"// SKIP
#import "/contrib/templates/std-tests/preset.typ": *
"#;

const GENERATED_CATEGORIES: &[&str] = &[
    "foundations",
    "html",
    "introspection",
    "layout",
    "loading",
    "math",
    "model",
    "pdf",
    "pdftags",
    "playground",
    "scripting",
    "styling",
    "symbols",
    "syntax",
    "text",
    "visualize",
    "playground.typ",
    // Categories generated by the pre-v0.14 upstream test layout.
    "bugs",
    "meta",
];

const LOCAL_LEGACY_CORPUS_FILES: &[&str] = &[
    "math/main.typ",
    "math/main.artifact.sir.in",
    "math/undergradmath.typ",
    "math/undergradmath.artifact.sir.in",
];

fn main() -> anyhow::Result<()> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let test_dir = &manifest_dir.join("../../../typst/tests/suite");
    let rewrite_dir = manifest_dir.join("../../fuzzers/corpora");
    let std_artifact_path = manifest_dir.join("../../tests/common/src/std_artifact.rs");

    cleanup_generated(&rewrite_dir)?;

    let mut test_files = WalkDir::new(test_dir)
        .into_iter()
        .par_bridge()
        .filter_map(|entry| {
            let entry = entry.unwrap();
            if entry.depth() == 0 {
                return None;
            }

            // if entry.path().starts_with("typ/benches") {
            //     return None;
            // }

            let src_path = entry.into_path();
            if src_path.extension() != Some(OsStr::new("typ")) {
                return None;
            }

            // if args.matches(&src_path) {
            //     Some(src_path)
            // } else {
            //     None
            // }
            Some(src_path)
        })
        .flat_map(|src_path| -> anyhow::Result<Vec<(String, String)>> {
            let text = std::fs::read_to_string(&src_path)?;
            let pref = src_path.strip_prefix(test_dir)?;

            let (cat, rewrite_path) = rewrite_target(&rewrite_dir, pref);
            if text.starts_with("// SKIP") || !text.lines().any(|line| line.starts_with("---")) {
                copy_support_file(&src_path, &rewrite_path)?;
                return Ok(vec![]);
            }

            let sections = parse_sections(&text);
            let mut rewrite_paths = vec![];
            for section in sections {
                if !section.is_render_target()
                    || section.has_expected_error()
                    || section.is_unsupported_for_corpus()
                {
                    continue;
                }

                let file_name = section.name;
                let rewrite_path = rewrite_path.with_file_name(format!("{file_name}.typ"));
                let test_path = rewrite_path.strip_prefix(&rewrite_dir)?.with_extension("");
                let test_path = path_to_slash(&test_path);

                eprintln!("scanned {cat:14} {test_path}...");

                rewrite_paths.push((cat.clone(), test_path));
                std::fs::create_dir_all(rewrite_path.parent().unwrap())?;
                std::fs::write(&rewrite_path, PRESET_HEADER.to_owned() + section.body)?;
            }

            Ok(rewrite_paths)
        })
        .flatten()
        .collect::<Vec<_>>();

    test_files.sort();
    let test_files = test_files
        .iter()
        .map(|s| format!("{s:?}"))
        .collect::<Vec<_>>()
        .join(",\n    ");

    std::fs::write(
        std_artifact_path,
        format!(
            r#"// This file is generated by `cargo run -p std --bin typst-ts-std-test`
#![cfg_attr(rustfmt, rustfmt_skip)]

pub const STD_TEST_FILES: &[(&str, &str)] = &[
    {test_files}
];
"#
        ),
    )?;

    Ok(())
}

struct Section<'a> {
    name: &'a str,
    attrs: Vec<&'a str>,
    body: &'a str,
}

impl Section<'_> {
    fn is_render_target(&self) -> bool {
        let has_render = self.attrs.contains(&"render");
        let has_non_render = self
            .attrs
            .iter()
            .any(|attr| matches!(*attr, "html" | "pdftags"));
        has_render || !has_non_render
    }

    fn has_expected_error(&self) -> bool {
        self.body
            .lines()
            .any(|line| line.trim_start().starts_with("// Error:"))
    }

    fn is_unsupported_for_corpus(&self) -> bool {
        self.body.contains("@test/") || self.body.contains(r#"read("./eval.typ")"#)
    }
}

fn parse_sections(text: &str) -> Vec<Section<'_>> {
    let mut sections = vec![];
    let mut current = None;

    for (offset, _) in text.match_indices("---") {
        if !text[..offset].ends_with('\n') && offset != 0 {
            continue;
        }

        let line_end = text[offset..]
            .find('\n')
            .map_or(text.len(), |end| offset + end);

        let line = &text[offset..line_end];
        let Some(header) = parse_header(line) else {
            continue;
        };

        if let Some((name, attrs, body_start)) = current.replace((header.0, header.1, line_end + 1))
        {
            sections.push(Section {
                name,
                attrs,
                body: text[body_start..offset].trim_end_matches(['\r', '\n']),
            });
        }
    }

    if let Some((name, attrs, body_start)) = current {
        sections.push(Section {
            name,
            attrs,
            body: text[body_start..].trim_end_matches(['\r', '\n']),
        });
    }

    sections
}

fn parse_header(line: &str) -> Option<(&str, Vec<&str>)> {
    let content = line.strip_prefix("---")?.strip_suffix("---")?.trim();
    let mut words = content.split_whitespace();
    let name = words.next()?;
    Some((name, words.collect()))
}

fn cleanup_generated(rewrite_dir: &Path) -> anyhow::Result<()> {
    for cat in GENERATED_CATEGORIES {
        let path = rewrite_dir.join(cat);
        if !path.exists() {
            continue;
        }

        for entry in WalkDir::new(&path).contents_first(true) {
            let entry = entry?;
            let path = entry.path();
            if entry.file_type().is_file() {
                if is_local_legacy_corpus_file(rewrite_dir, path) {
                    continue;
                }

                if path.extension() == Some(OsStr::new("typ")) || is_generated_artifact(path) {
                    fs::remove_file(path)?;
                }
            } else if entry.file_type().is_dir() {
                let _ = fs::remove_dir(path);
            }
        }
    }

    Ok(())
}

fn is_local_legacy_corpus_file(rewrite_dir: &Path, path: &Path) -> bool {
    let Ok(relative) = path.strip_prefix(rewrite_dir) else {
        return false;
    };

    let relative = path_to_slash(relative);
    LOCAL_LEGACY_CORPUS_FILES.contains(&relative.as_str())
}

fn is_generated_artifact(path: &Path) -> bool {
    let name = path
        .file_name()
        .map(|name| name.to_string_lossy())
        .unwrap_or_default();

    name.contains(".artifact.")
        || name.ends_with(".ast.ansi.text")
        || path.extension() == Some(OsStr::new("pdf"))
        || path.extension() == Some(OsStr::new("txt"))
}

fn rewrite_target(rewrite_dir: &Path, pref: &Path) -> (String, PathBuf) {
    let components = pref.components().collect::<Vec<_>>();
    if components.len() == 1 {
        let stem = pref.file_stem().unwrap().to_string_lossy().to_string();
        return (stem.clone(), rewrite_dir.join(stem).join(pref));
    }

    let cat = components[0].as_os_str().to_string_lossy().to_string();
    (cat, rewrite_dir.join(pref))
}

fn copy_support_file(src_path: &Path, rewrite_path: &Path) -> anyhow::Result<()> {
    if let Some(parent) = rewrite_path.parent() {
        fs::create_dir_all(parent)?;
    }
    let text = fs::read_to_string(src_path)?;
    let text = text
        .strip_prefix("// SKIP")
        .map(|rest| rest.trim_start_matches(['\r', '\n']))
        .unwrap_or(&text);
    fs::write(rewrite_path, format!("{SUPPORT_HEADER}{text}"))?;
    Ok(())
}

fn path_to_slash(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}
